### ISSUE TITLE
App drawer - when clicking on app, the options could be sorted differently

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#105]
**Is your feature request related to a problem? Please describe.**
Putting the Uninstall option on the first place, where you usually first look, puts it into the top, best option to take. The top option should be Open

**Describe the solution you'd like**
Sorting (could be):
1. Open
2. Add Shortcut
3. Uninstall

**Comment by Aaron-von-Awesome** [comment]
I agree with this observation.  The first thing I want to take is "Uninstall" because I am so used to the first selection being the primary function.
