### ISSUE TITLE
[Alarms] some improvements & a tiny bug

### ISSUE THREAD

**Issue by DJCrashdummy** [UriahShaulMandel/BaldPhone#11]
- [x] when creating a new alarm, a button (beside *"Only once"*) to activate all weekdays at once - like available at the *"Pills"* - may ease the things for some people.
  *BTW: is there a way to reorder the weekdays based on the localization automatically, because a bunch of regions exists, where the week does not start on Sunday, but Monday (or whenever else)?*

- [x] sorting the alarms at the overview by their next time they will ring (and not by their creation time) may be reasonable.
  i can imagine that some may ask for an alphabetical sorting... but if, i would just make this an optional feature and not the default.

- [x] when no name for an alarm is chosen viewing *"Alarm"* at the overview (or even setting it as its actual name?) as it is done for a *"Timer"* may help to avoid confusion.

- [x] BaldPhone crashes when a "one-time alarm" occurs while you are viewing the alarm screen and then try to edit the already deleted alarm (funny: turning the already deleted alarm on/off "works" without any complains).
  the best solution would be to also refresh the overview (as it is done when you manually delete an alarm) after an alarm was deleted automatically.

**Comment by UriahShaulMandel** [comment]
On it :)

**Comment by UriahShaulMandel** [comment]
All points were addressed, except localization of days, which was moved to issue #1 
Great ideas, Thank you very much! :)
