### ISSUE TITLE
Website bug: Apk download link on the official website gives error 404 and doesn't download apk

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#120]
**Describe the bug**
The download link on the official website doesn't download an apk and it throws error 404 at me.

**To Reproduce**
1. Go to website
2. Click on [Download now](https://github.com/UriahShaulMandel/BaldPhone/releases/download/92/app-release.apk)
3. See error 404

**Screenshots**
![hbMWaXY0gn](https://user-images.githubusercontent.com/50620416/68907312-a88b5f00-0747-11ea-9888-897333b8738d.png)

**Additional context**
Redirrect link on the website: https://github.com/UriahShaulMandel/BaldPhone/releases/download/92/app-release.apk

Device: Desktop PC
OS: Windows 10

**Comment by UriahShaulMandel** [comment]
Thanks!
Fixed
