### ISSUE TITLE
Critical bug, Recents - In the version 11.9.0, the contact names in the Recents are no longer visible

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#122]
**Describe the bug**
- In the latest BaldPhone 11.9.0, The contact names in the Recents (calls) have dissappeared, and all the contacts are treated as the not-saved contacts. That's on second device from a family member. On my phone, today's Recents (today i updated) are now regarded as not-saved contacts...

**To Reproduce**
- Steps to reproduce the behavior:
1. Go to Recents
2. See all the saved contacts as unknown contacts (just numbers displayed, no names)

**Expected behavior**
- The Recents menu should display all your contact names.

**Phone(please complete the following information, it can be found in the settings under Technical Information):**
 - API Level: 24 (device 1)- all the recents are unknown as contacts
- API Level: 28 (device 2)- The recents from the new update (today) are unknown contacts, and older ones are looking ok (yesterday on).
 - BaldPhone Version name 11.9.0

**Additional context**
- I think this is a serious bug that will leave a lot of rage / heads scratching and i think it should be immediately removed/delayed, until this bug is fixed.

- I cleared the program data on the new version and the problem is still there, so it's a bug in the new version.
- reinstalled the 1.8.0 and it's ok again.

**Comment by UriahShaulMandel** [comment]
Oh no, thank you for letting me know fast before too many have updated,
Can you check if this APK works? I think it should work.
Please let me know if it's working as fast as possible,
and thanks again!
[baldphone_critical_bug_test.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3852506/baldphone_critical_bug_test.zip)

**Comment by aha999** [comment]
It works, it fixes the bug.

**Comment by UriahShaulMandel** [comment]
Thank you very much! 
I uploaded 11.9.1.
