### ISSUE TITLE
Add Option to replace functionality of Tile at Main screen

### ISSUE THREAD

**Issue by ytidhar** [UriahShaulMandel/BaldPhone#139]
Add option to change app in tiles at main screen/
for example to replace the pill with email.

**Comment by aha999** [comment]
That would've been pretty good, for example i would also like to replace the assistant on home screen, because it's not supported in our country or if some people don't speak english...

https://github.com/UriahShaulMandel/BaldPhone/issues/69

**Comment by UriahShaulMandel** [comment]
I'll add this option :)

**Comment by Aokromes** [comment]
this was already implemented on https://github.com/UriahShaulMandel/BaldPhone/releases/tag/95 no?

**Comment by UriahShaulMandel** [comment]
Yes, Thanks for the reminder :)
Marking as fixed
