### ISSUE TITLE
Use colors in ui

### ISSUE THREAD

**Issue by ytidhar** [UriahShaulMandel/BaldPhone#140]
for users it may be easier to remember the button to press if it have color
i suggest to add option to have colored ui as in this app 

[https://play.google.com/store/apps/details?id=com.primuxtech.launcher](url)

**Comment by aha999** [comment]
my opinion as user is, I think it could be an optional theme, to maybe make things more colorful, but i think the current one has cleaner look.
Themes would be pretty nice

**Comment by UriahShaulMandel** [comment]
Cool Idea!
I'll add more themes, colorful theme sound really cool.

**Comment by UriahShaulMandel** [comment]
Added colorful setting
![image](https://user-images.githubusercontent.com/43012268/71616759-88f9aa00-2bc0-11ea-8357-980e62eda1e2.png)
