### ISSUE TITLE
App Option "Uninstall" does not Uninstall App 

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [UriahShaulMandel/BaldPhone#146]
**Describe the bug**
App drawer option of "Uninstall" does not uninstall the app.

**To Reproduce**
1. On Home screen, tap "Apps"
2. Tap an App, and the options "Uninstall", "Open", and "Add Shortcut" appear
3. Tap "Uninstall"
4. You are presented with an "Are you sure..." modal, tap "Yes"
5. Modal disappears, App remains in the App Drawer, and App is *not* uninstalled  

**Expected behavior**
Given that the User has opened the App Drawer, when an App is tapped and the User selects the "Uninstall" option, and confirms the uninstall, then the App should be uninstalled from the device.

**Screenshots**
None added

**Phone(please complete the following information, it can be found in the settings under Technical Information):**
 - API Level: 28
 - Version name: 11.9.1
 - Version Code:93
 - Flavor: fDroid
 - Manufacturer: Google
 - Brand: google
 - Device: marlin
 - Model: Pixel XL

**Additional context**
N/A

**Comment by aha999** [comment]
I agree. Also doesn't work on my 11.9.1. (all the permissions given to baldphone)
This bug wasn't present in the previous versions.

**Comment by UriahShaulMandel** [comment]
Hi,
First things first, @Aaron-von-Awesome thank you for the patreon contribution!
about the bug, I found out it has to do with android API 28, I'll implement this solution:
https://stackoverflow.com/a/21854473

**Comment by aha999** [comment]
@Aaron-von-Awesome,
Tip: Pixel XL is manufactured by HTC:

https://en.m.wikipedia.org/wiki/Pixel_(smartphone)
