### ISSUE TITLE
Contacts: the contact picture is too big in the contact info.

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#150]
**Is your feature request related to a problem? Please describe.**
When you open a contact that has a picture, the contact picture is huge, so wide as the display.

**Describe the solution you'd like**
Make the contact picture a lot smaller. Add rounded edges so it looks better.

![mIIn0KAZTv](https://user-images.githubusercontent.com/50620416/69905439-bf6eba00-13b3-11ea-849a-fafbf00e5549.png)

**Comment by UriahShaulMandel** [comment]
Already fixed, forgot to close the issue :)
