### ISSUE TITLE
Contacts/Dialer: The contact icons with letters could each have specific randomized colors for the circle background

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#154]
**Is your feature request related to a problem? Please describe.**
- The contact icons with letters inside all look the same

**Describe the solution you'd like**
- A colored letter background in the contact picture area if the contact doesn't have a picture assigned.

**Describe alternatives you've considered**
- If it happens that the colors would look out-of-place or too strong colored for the current theme, It could also be reserved/planned for a 'color/vibrant' theme option in the future.
- Or the colors could be added to the current theme, and be a little gentler toned, that would be awesome.

**Additional context**
- Example in the screenshot:

![PL6cO7mR8M](https://user-images.githubusercontent.com/50620416/70381585-185ac700-194d-11ea-83f4-f98d496d3b3b.png)

**Comment by UriahShaulMandel** [comment]
Cool!
Note to self - here's a way to randomize colors which looks ok with the background:
https://stackoverflow.com/a/4247219
