### ISSUE TITLE
App-Menu: Optional sorting of apps into one grid without search letters in-between apps.

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#158]
**Is your feature request related to a problem? Please describe.**
- If you don't have a lot of apps, you still have to scroll down between the rows and search for the app.

**Describe the solution you'd like**
- Optional option to sort the apps into one grid without (search) letters in-between rows. It becomes more compact, shorter to scroll and it can be faster to find the app by the logo.

**Comment by UriahShaulMandel** [comment]
Cool idea!

**Comment by K0media** [comment]
@UriahShaulMandel, what do you think about this?
![image](https://user-images.githubusercontent.com/22375465/144173856-06e4011e-a008-4baa-8353-d21a6cbaea7b.png)

Something good to implement or never mind?
