### ISSUE TITLE
[FR] Missing information from the statusbar

### ISSUE THREAD

**Issue by Primokorn** [UriahShaulMandel/BaldPhone#18]
**Is your feature request related to a problem? Please describe.**
Missing information about the signal, mobile data, alarm, Wi-Fi...

**Describe the solution you'd like**
Additional information next to the clock for example.

**Describe alternatives you've considered**
To add an option to show/hide the system statusbar.

Thanks.

**Comment by UriahShaulMandel** [comment]
Hi, and thank you for submitting the issue!
I'll add an option to show/hide the system statusbar, looks like it's the best solution and it's also fairly simple.

**Comment by UriahShaulMandel** [comment]
Added an option to control where the status bar is being shown:
![image](https://user-images.githubusercontent.com/43012268/61176394-c776ba80-a5c8-11e9-8d39-07e6dbcaaaf8.png)
The update is going through tests and will be released tomorrow.

**Comment by Primokorn** [comment]
@UriahShaulMandel Please add the new strings so that I can translate before the official release. Thanks!
