### ISSUE TITLE
Replacing assistant

### ISSUE THREAD

**Issue by Primokorn** [UriahShaulMandel/BaldPhone#19]
**Describe the bug**
Can't get results with the Assistant.

**To Reproduce**
1. Open "Assistant" fromi the main screen
2. Tap on the big Android icon
3. Say "Test" or "What's the weather like today?"
The toast message either uses the string "___app_was_not_found" or "please_repeat_that".

**Expected behavior**
Launch the web browser for a search or open the requested app.

**Screenshots**
![photo_2019-07-10_10-04-25](https://user-images.githubusercontent.com/5938828/60951841-4edada00-a2fa-11e9-98cb-4f0aeb80b152.jpg)

**Phone(please complete the following information, it can be found in the settings under Technical Information):**
 - API Level: [e.g. 29]
 - BaldPhone Version name [e.g. 11.3.1]

**Comment by UriahShaulMandel** [comment]
I've stopped development on the assistant a long time ago, thinking of replacing it with the google assistant instead. What do you think?

**Comment by Primokorn** [comment]
I fully agree but guys who want to see your app on F-Droid won't appreciate...
Since the app is mainly for the elderly, the priority is the assistant instead of F-Droid. My grandmother doesn't care where the app is published but she appreciates Google Assistant :)

**Comment by UriahShaulMandel** [comment]
Fixed in [this](https://github.com/UriahShaulMandel/BaldPhone/commit/6e6d0e42b595bb01643f00336da513afa29134c5) commit
