### ISSUE TITLE
Baldphone donation icon change request

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#198]
I think that the baldphone icon in the app could be changed from the money (dollar) sign, to something like in the pic (with same color as other icons), to implicate a good deed, instead of a dollar sign that represents buying something imo...

Request for this style of icon:

![slika](https://user-images.githubusercontent.com/50620416/72740185-782bcb00-3ba5-11ea-84e2-77733903ecee.png)

Currently:

![slika](https://user-images.githubusercontent.com/50620416/72741318-b2966780-3ba7-11ea-9eb8-dbf8e3f6954b.png)

**Comment by UriahShaulMandel** [comment]
Thanks! fixing
