### ISSUE TITLE
Texts overlap in the Alarm screen

### ISSUE THREAD

**Issue by Primokorn** [UriahShaulMandel/BaldPhone#20]
**Describe the bug**
When using a big font texts overlap.

**To Reproduce**
1. Increase the size of the font (and maybe your DPI)
2. Create a new alarm 
3. See error

**Expected behavior**
Line breaks shoudl help. The problem is worse on the phone of my grandmother (higher DPI).

**Screenshots**
![Screenshot_BaldPhone_20190712-125405](https://user-images.githubusercontent.com/5938828/61130607-55628080-a4b7-11e9-8a46-de4baa2dc8f6.png)

**Phone(please complete the following information, it can be found in the settings under Technical Information):**
* API Level: [e.g. 29]
* BaldPhone Version name [e.g. 11.3.1]

**Comment by UriahShaulMandel** [comment]
Pushed an update fixing this issue.
The update is going through tests and will be released tomorrow.
