### ISSUE TITLE
Replace Whatsapp recommendation shortcut with Signal

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#230]
**Is your feature request related to a problem? Please describe.**
The recommended online messaging app on the baldphone homescreen is closed-source WhatsApp, which is owned by Facebook and not privacy is not in their best interest.

**Describe the solution you'd like**
It would be awesome if you replaced Whatsapp with "[Signal messenger](https://signal.org/)" shortcut. Signal is an [open-source](https://github.com/signalapp) messaging platform that has by default encrypted messages, calls and video-calls, reaction stickers etc. It has all the basic functions other messaging platforms have. It only requires a phone number verification to use (like other messaging platforms) and then it shows you your contacts that already use Signal so you can message them immediately. It already has a big user base and it's growing every day. It has apps for Android, iOS, MacOS, Windows, Linux.

**Additional info**
- If anyone wanted to specifically use Whatsapp or any other platform, like Viber etc. they will have to download it anyways on the play store.
- On the other note, this is just a shortcut change icon to the Play Store, so it could at least be promoting open source and secure messenger that a lot of people are using already and you can invite anyone's number in one click if they're not.

Articles:
- [Signal Is Finally Bringing Its Secure Messaging to the Masses](https://www.wired.com/story/signal-encrypted-messaging-features-mainstream/)
- [If you value your privacy, switch to Signal as your messaging app now](https://www.fastcompany.com/90335034/if-you-value-your-privacy-switch-to-signal-as-your-messaging-app-now)
- [Ditch All Those Other Messaging Apps: Here's Why You Should Use Signal](https://www.wired.com/story/ditch-all-those-other-messaging-apps-heres-why-you-should-use-signal/)
- [Stop Using WhatsApp If You Care About Your Privacy](https://lifehacker.com/stop-using-whatsapp-if-you-care-about-your-privacy-1825719172)

![slika](https://user-images.githubusercontent.com/50620416/74579934-04f85780-4f9f-11ea-9478-ebc18b6088ad.png)

**Comment by RahiAkherajot** [comment]
It is not available on web, instead riot.im is available on every platform as it can be accessed through a web browser.

**Comment by aha999** [comment]
Signal is simple to use with an interface like an SMS app and It's easier for elderly to create an account (just a phone number as a confirmation) and that's it, you will appear under your name in the other users' signal contacts that have your number.
To send a new message in Signal you just press a pencil button and it asks you who you'd like to contact among your (signal) contacts, so it's same looking like SMS messaging. On riot, it opens a submenu of Start chat, Create room and Join room. Also Riot has many submenus that can be confusing.

> Riot.im does not encrypt chats by default, so that’s something to be aware of. Also, in my opinion, Matrix is focused more on large group chats with multiple channels (like IRC or Slack), whereas Signal is more focused on 1-1 or small group chats (like WhatsApp or other messaging apps). [quote](https://www.reddit.com/r/signal/comments/diyitk/what_do_you_think_about_riotim/)

> Signal - a secure replacement for your default sms messenger
Riot (matrix network) - public chatrooms, forums. [quote](https://www.reddit.com/r/signal/comments/dda02x/riotim_vs_signal/f2febnb?utm_source=share&utm_medium=web2x)

IMO, For elderly/disabled etc., Signal would be definitely better, because of the UX SMS-like simplicity and Riot would be more suitable for techy people because it has too many visible options everywhere.

**Comment by RahiAkherajot** [comment]
However it depends on user
It would be great if Baldphone supports every messenger app and shows options only for installed apps. It can recommend open source apps to users.

**Comment by rms-joe** [comment]
completely agree. I came over to request an option to replace what's app button with any messenger of your choice.

**Comment by UriahShaulMandel** [comment]
@rms-joe 
Hi, forgot to update this issue.
Its solved! :)
Go to settings->personalization->edit home screen
And you can change it there
Uriah

**Comment by breversa** [comment]
I'm glad that you can change to another app !

However,
1. I think its privacy-damaging to promote WhatsApp by default.
2. I've set up Signal as the default app for a client, but when they tap on the icon, it's Signal's *setting* menu that opens (which was unacceptable for them, and they decided to switch to the default SMS app instead). I'm not sure if that's a Bald Phone or Signal issue though. Maybe an Activity issue ? What do you think ?
