### ISSUE TITLE
Add a counter of users & monthly active users

### ISSUE THREAD

**Issue by UriahShaulMandel** [UriahShaulMandel/BaldPhone#26]
As of now, because I wanted to keep BaldPhone FOSS, and didn't include [crashlytics analytics](https://github.com/UriahShaulMandel/BaldPhone/issues/7), there is no way of knowing how many users downloaded BaldPhone, and how many actually use it as their HomeScreen. 

There should be a way of counting those numbers.

Ideas I had so far:
 ## Using an [open-source analytics tool](https://github.com/segmentio/analytics-android)
pros 
- Free until 1000 monthly active users
- Simple API which will be easy to integrate

 cons
  - 1000 monthly active users for free is nice, but if it'll pass then $120 per month base (the price for 10,000) is something I won't be able to afford for a non-profit project

 ## Send each user as a crash via acra & [tracepot](https://www.tracepot.com/)
pros 
- Already implemented in BaldPhone so will take no time to implement
- If tracepot is closed another backend can be used instead (with payment, sadly)

 cons
- [tracepot](https://www.tracepot.com/) is limited to 30,000 crash reports per month, and if this line is crossed there is nothing to do
- The company is [closed](https://www.tracepot.com/#features) and may close the free tool anytime
- Not made for this purpose

 ## Create my own simple server
pros
- most reliable solution
- no limit of users

 cons
- Can take a lot of time, which I barely have
- Needs constant maintenance
- Money which comes from my own pocket

# Would be glad to hear your suggestions and opinions!

**Comment by UriahShaulMandel** [comment]
@IzzySoft ,
Perhaps you know how other apps in your repo, or in the official F-Droid repo get this information?
I get asked **a lot** how many users use BaldPhone, and it's important information,
I respect users privacy and do not want to use Crashlytics, but I really need a way to get this information...

**Comment by UriahShaulMandel** [comment]
Thank @idoheinemann Very much!
He created a server dedicated to checking users versions, so I'll be able to know how many users use BaldPhone and how many of them are active (updated to the latest version)
Thanks!!

**Comment by UriahShaulMandel** [comment]
Important to mention - the server only saves two things:
UUID - a random number generated when the app first opens using the UUID algorithm
Version Code - the current version code the user is running on

This way no one can track anything back to the users and the app continues to keep the user's privacy safe :)

**Comment by IzzySoft** [comment]
I was too slow… But to answer your question anyway: No, for privacy reasons we do NOT collect any such information on F-Droid. I guess you'll create some unique hash (e.g. based on the unix timestamp and the IP address assigned at that moment) at install time, and use that to identify an install (as that would count as anonymous and thus not necessarily result in the Tracking AntiFeature – I know you value privacy as much as we do, so I count on that :wink:)

Ah yes, again your answer comes faster :laughing:
