### ISSUE TITLE
Provide guidance to begin translating using Git only (instead of sending Uriah a file).

### ISSUE THREAD

**Issue by DBC-226** [UriahShaulMandel/BaldPhone#284]
**Is your feature request related to a problem? Please describe.**
From https://github.com/UriahShaulMandel/BaldPhone/blob/master/translating/TRANSLATING.md I get directions to edit an existing translation using Git, but if I want to start translation of a new langauage (and I'd guess that's desirable), there's only an option to send you a finished file.
However, I'd really like to just use "the regular Git-features" to do so and perhaps other will too, so to enable more people to contribute, why not provide a short-ish description of how to do that?

**Describe the solution you'd like**
Could be as simple as:
1. Fork the project
2. Create a branch in your forked project
3. Copy file X to new folder values-(RFC language code) + add your language to the list of languages in file Y
4. Commit changes to your own branch
5. Create a draft pull request in the original project (with a bit of description)
...
n-1. Finalize pull request
n. Profit!

**Additional context**
I guess this could also lessen the work for you creating new translations a bit, @UriahShaulMandel? :slightly_smiling_face:

You're welcome to assign this issue to me, but please give me some guidance on what is required for creating a new language for BaldPhone.

**Comment by DBC-226** [comment]
You're welcome to assign this issue to me, but please give me some guidance on what is required for creating a new language for BaldPhone.

**Comment by UriahShaulMandel** [comment]
Sounds really good! Thanks for the idea and the contribution!

**Comment by UriahShaulMandel** [comment]
I changed it, feel free to change it as well if you have a better way to write it, and i'll confirm the pr
Thanks

**Comment by DBC-226** [comment]
Great! 

Is that all there is to it? 
By having the folder "values-[RFC language code]" the language will be an option in the app in next release - or is it necessary to make some other changes, e.g. add is an option in some files?
I think that by being very vocal about what's required, you can get some better quality pull requests and it's less work for you.

I'd also be great if we the option could include guidance for getting the new language added to the screenshots on https://github.com/UriahShaulMandel/BaldPhoneCompanion. 
Those are a huge help when translating, because you can see the context for many strings.
You should also consider adding a few more different screens to that collection.

**Comment by UriahShaulMandel** [comment]
By having the folder "values-[RFC language code]" the language will indeed be an option in the app in next release,
no other code needed :)
`I think that by being very vocal about what's required, you can get some better quality pull requests and it's less work for you.`
Agree, thank you for proposing this change, and please let me know if you have other things you think should be changed :)



`I'd also be great if we the option could include guidance for getting the new language added to the screenshots on https://github.com/UriahShaulMandel/BaldPhoneCompanion.`

There's a problem with this repo, When I'll have a bit more time I'll do it as you said (will take 1-2 work days which I Simply dont have, due to heavy work in my job)

Thanks,
Uriah

**Comment by DBC-226** [comment]
Sounds good! 
I suggest keeping this issue open and then I'll make a commit at some point expanding a bit on the guide for creating new languages and referring to this issue.

**Comment by UriahShaulMandel** [comment]
👍

**Comment by UriahShaulMandel** [comment]
Fixed!
Check out https://github.com/UriahShaulMandel/BaldPhone/blob/master/translating/TRANSLATING.md
Thanks!
