### ISSUE TITLE
Option to add one time alarm that doesn't get deleted once activated

### ISSUE THREAD

**Issue by idoheinemann** [UriahShaulMandel/BaldPhone#41]
I have some alarms on my phone that are usually turned off, sometimes I need those alarms for one time, and using the BaldPhone interface, I have to create them all over again.

My suggestion is to add an option (or maybe even make it the default) for one time alarms not to be deleted after activated, but instead, be turned off until the user manually activates them or manually deletes them.

**Comment by UriahShaulMandel** [comment]
Right!
One time alarms should have never been deleted after one use, only Timers should have.
Will be fixed today, 
Thanks!
