### ISSUE TITLE
Change default apps on home

### ISSUE THREAD

**Issue by tmschmitz** [UriahShaulMandel/BaldPhone#46]
I would like to change the default apps on home screen. It is not obvious how to do that.

**Comment by UriahShaulMandel** [comment]
Hi there, and thank you for your feedback!
Changing the default apps on the home screen is not possible yet, Only the WhatsApp app can be changed in `Settings -> Personalization -> Custom App`
With that said, **I will add a way to change other apps in the home screen too**, following your request :)
This will probably be up in version 11.5.0, I'll post updates about it in this thread.

**Comment by tmschmitz** [comment]
Thanks for the fast response. I wanted the Dexcom app to be on the front screen for my mother. She rarely uses the phone for anything else anyway, and certainly not WhatsApp...
