### ISSUE TITLE
"Internet" Shortcut Not Working

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [UriahShaulMandel/BaldPhone#47]
**Describe the bug**
I have a Pixel XL running LineageOS 16.0 (20190822-nightly), and on the second screen (the screen with "Settings", "Internet", "Maps", etc.), upon tapping on "Internet", I am receiving the following error message: "No matching app was found!".

**To Reproduce**
1.  ![Screenshot_20190823-165647_BaldPhone](https://user-images.githubusercontent.com/6528788/63625955-418a5e00-c5cf-11e9-9e81-fe99f6b982ad.png)

2.  ![Screenshot_20190823-165652_BaldPhone](https://user-images.githubusercontent.com/6528788/63625962-4a7b2f80-c5cf-11e9-8e15-fde42a5cb27b.png)

**Expected behavior**
Given that I tap on the "Internet" button, and I have a default browser app installed and set as default, then my default web browser app should open, so that I can surf the web on my phone.

**Screenshots**
See above.

**Phone(please complete the following information, it can be found in the settings under Technical Information):**
 - API Level: 28
 - BaldPhone Version Name:  11.4.2 / Version Code:  83

**Comment by UriahShaulMandel** [comment]
Hi, and thank you for using BaldPhone!
Checking out what causing this issue and Fixing it now :)

**Comment by UriahShaulMandel** [comment]
Hi, it should be fixed now :),
can you make sure it's working, before I'm publishing the release?
Note: Its signed with BaldPhone's key and not with F-Droid key, so you may have to uninstall the current version of BaldPhone first...

Fixed apk link: [app-baldUpdates-release.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3536452/app-baldUpdates-release.zip)


And thank you very much for opening this issue :)

**Comment by UriahShaulMandel** [comment]
Sorry, Apparently there was another bug, something to do with behavior change on marshmallow and above. Please check out this link instead:
[app-baldUpdates-release.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3536608/app-baldUpdates-release.zip)

**Comment by Aaron-von-Awesome** [comment]
Howdy @UriahShaulMandel - I have tested the APK you provided, and the "Internet" button is working as expected.

Thank you very much for fixing it, and thank you very much for this project!  I'm look forward to having my Mother use this on her very first smartphone :smiley:
