### ISSUE TITLE
[Feature Request] DTMF Sounds whilst using Dialer dial pad

### ISSUE THREAD

**Issue by Aaron-von-Awesome** [UriahShaulMandel/BaldPhone#48]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Given that the User is using the Dialer to dial a number, and the "Accessibility Level" is set to "Regular level", when the User enters the phone number by pressing a number on the dialer keypad, then the User will hear the DTMF touch-tones sounds for each number entered.

Given that the User is using the Dialer to dial a number, and the "Accessibility Level" is set to "Medium level", when the User enters the phone number by long-pressing a number on the dialer keypad, then the User will hear the DTMF touch-tones sounds for each number entered.

**Describe alternatives you've considered**
N/A

**Additional context**
- DTMF sounds example
    - https://www.youtube.com/watch?v=b99h3S7YpHk

![Screenshot_20190823-231818_BaldPhone](https://user-images.githubusercontent.com/6528788/63632158-72828700-c5ff-11e9-9b5d-7fdcf6377442.png)

![Screenshot_20190823-231937_BaldPhone](https://user-images.githubusercontent.com/6528788/63632180-a8c00680-c5ff-11e9-8a50-2b1b024a5121.png)

![Screenshot_20190823-231944_BaldPhone](https://user-images.githubusercontent.com/6528788/63632163-7f9f7600-c5ff-11e9-993a-5642140186ce.png)

![Screenshot_20190823-231950_BaldPhone](https://user-images.githubusercontent.com/6528788/63632168-84642a00-c5ff-11e9-8e6c-13ff16b4ee6b.png)

**Comment by UriahShaulMandel** [comment]
Cool idea! I'm on it.
Note to self: https://developer.android.com/reference/android/media/ToneGenerator

**Comment by UriahShaulMandel** [comment]
Fixed, Will be up in the next version :),
Thank you for suggesting this cool idea!
If you want to try it before the release, you can download it here:
[app-baldUpdates-release.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3537531/app-baldUpdates-release.zip)
