### ISSUE TITLE
minor enhancements

### ISSUE THREAD

**Issue by DJCrashdummy** [UriahShaulMandel/BaldPhone#51]
this are little suggestions i consider as helpful and would be nice to have, but some of them (especially the first) may be too much of a "(hidden) function" for some people and confuse them, so i guess they just should be optional: (*though i'm not sure if active/inactive should be the default.*)

- [ ] i'm soo used to tap on the clock/time at my normal launcher to get to the time-/alarm-app... and i guess this would be a nice function for baldphone too. - and if you are thinking further to a possibly more flexible arrangement of buttons/functions of the main screen, it can free one slot for other functions/buttons.

- [ ] i also kind of like to get remembered of low energy (even while using an app) by highlighting the usual status bar in red... it would be nice if the "group-colour" of the "baldphone-statusbar" would also change, for people who never display the usual status bar and don't have a status LED.
*i'm still not sure if this should be an extra setting, or triggered automatically when the usual status bar is hidden.* :thinking: 

- [ ] the animation of the bell in case of pending notifications is really nice :+1:, but how about additionally colouring the bell (as it is done with the torch and somehow at low energy with the battery) for an immediate response? - this will also make it a breeze for people with parkinson disease (and no notification LED) to recognise pending notifications.

**Comment by UriahShaulMandel** [comment]
Great ideas! I'm opening an issue regarding all of those issues.
Thanks! :)

**Comment by UriahShaulMandel** [comment]
I've opened #52 and #53 .
I didn't fully understand the last idea:

> the animation of the bell in case of pending notifications is really nice 👍, but how about additionally colouring the bell (as it is done with the torch and somehow at low energy with the battery) for an immediate response? - this will also make it a breeze for people with parkinson disease (and no notification LED) to recognise pending notifications.

You want me to color the bell red always when there are more than X notifications?, or to color the bell according to each notification, like Samsung does with their devices?

**Comment by DJCrashdummy** [comment]
well... i like to have an immediate response/indication, if there are notifications pending resp. things which need my attention or not.
at the "usual android status bar" there are the various notification icons on its left side and some devices even have a notification LED... but without one of them and just baldphone, it is not that easy to tell. - the animation of the notification bell in baldphones status bar is cool, but its not that easy to catch (especially if you are a little bit shaky or worse... keyword parkinson disease).

thus the idea is to (additionally) colour the notification bell to instantly and easily see if there is a notification pending.

- - -

:bulb: your response lead me to additional ideas:

- [ ] a more advanced behaviour/setting may be interesting... in case of you have persistent notifications an option to set the number of notifications to start colouring the bell can be handy.
- [ ] you can even add a second optional & adjustable limit to change the colour (and hence indicate something like "too much" notifications).
-> *lets say default starting colouring the bell yellow with 1 notification and with 10 notifications getting red.*
- [ ] and the cherry on the cake would be a smooth transition from the first colour to the other. - so you have the possibility with a fleeting glimps to get a clue, wether it is just 1 notification or rather 9 (in case of my example).

- - -

hmm... now i don't get this:
> color the bell according to each notification, like Samsung does with their devices?

i don't have an actual samsung device and don't know what they are doing. :question:

**Comment by DJCrashdummy** [comment]
*sorry for posting this also in this accumulated issue, but for the initial post i thought these are so minor (and even optional) enhancements, that they don't need/deserve separate issues... and the last post started as a direct answer, so...
maybe we should also open an own issue (if you are also ok with the 3rd idea) or perhaps it may be easier to rename this issue and modify/update the initial post as the other two ideas are already covered at separate issues. (i'm thinking of strike trough the first two ideas and mention/link the dedicated issues.)*

**Comment by UriahShaulMandel** [comment]
> 💡 your response lead me to additional ideas:
> 
> * [ ]  a more advanced behaviour/setting may be interesting... in case of you have persistent notifications an option to set the number of notifications to start colouring the bell can be handy.
> * [ ]  you can even add a second optional & adjustable limit to change the colour (and hence indicate something like "too much" notifications).
>   -> _lets say default starting colouring the bell yellow with 1 notification and with 10 notifications getting red._
> * [ ]  and the cherry on the cake would be a smooth transition from the first colour to the other. - so you have the possibility with a fleeting glimps to get a clue, wether it is just 1 notification or rather 9 (in case of my example).


I really like these ideas!
can you open a new issue with this text? It's looks a bit weird when I open new issues lol. Thank you very much!

**Comment by UriahShaulMandel** [comment]
@DJCrashdummy  Just wanted to thank you for your great help and suggestions, You really make BaldPhone better. Thank you! :)

**Comment by DJCrashdummy** [comment]
@UriahShaulMandel you are constantly improving baldphone... i'm just throwing thoughts, ideas and suggestions at you, which is a pleasure for me. :wink: 

> It's looks a bit weird when I open new issues lol.

i know what you mean... but it is not so odd and done every now and then: IMHO if it is a issue created by yourself and even with just your content, it is thus a kind of collaboration and giving others the possibility to follow the development and to participate.
