### ISSUE TITLE
immediate indication for pending notifications

### ISSUE THREAD

**Issue by DJCrashdummy** [UriahShaulMandel/BaldPhone#56]
this is part of a follow up from #51:

**Is your feature request related to a problem? Please describe.**
> at the "usual android status bar" there are the various notification icons on its left side and some devices even have a notification LED... but without one of them and just baldphone, it is not that easy to tell. - the animation of the notification bell in baldphones status bar is cool, but its not that easy to catch (especially if you are a little bit shaky or worse... keyword parkinson disease).

**Describe the solution you'd like**
> - [ ] thus the idea is to (additionally) colour the notification bell to instantly and easily see if there is a notification pending.

**Describe alternatives/*additional ideas* you've considered**
> - [ ] a more advanced behaviour/setting may be interesting... in case of you have persistent notifications an option to set the number of notifications to start colouring the bell can be handy.
> - [ ] you can even add a second optional & adjustable limit to change the colour (and hence indicate something like "too much" notifications).
-> *lets say default starting colouring the bell yellow with 1 notification and with 10 notifications getting red.*
> - [ ] and the cherry on the cake would be a smooth transition from the first colour to the other. - so you have the possibility with a fleeting glimps to get a clue, wether it is just 1 notification or rather 9 (in case of my example).

**Comment by UriahShaulMandel** [comment]
I started to write some code, and that's what I have till now.
From 5 notifications and up, it'll become more and more red and will do the bell animation more and more frequently. IMO it looks really cool. See this video (I sented notifications in the background. The bell sometimes stops because when a new notification is being sent it stops for 5 seconds): 

[video.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3613159/video.zip)

**Comment by UriahShaulMandel** [comment]
The end of the video is the important part

**Comment by UriahShaulMandel** [comment]
You can test out the changes I made this far here:
[BaldPhone_battery_and_notifications_test.zip](https://github.com/UriahShaulMandel/BaldPhone/files/3613171/BaldPhone_battery_and_notifications_test.zip)

**Comment by UriahShaulMandel** [comment]
Fixed
