### ISSUE TITLE
Alarm does not work when phone is locked.

### ISSUE THREAD

**Issue by EnfrigFalco** [UriahShaulMandel/BaldPhone#570]
**Describe the bug**
Alarm does not sound work when phone is locked. When unlocked the alarm sounds.

**To Reproduce**
1. Go to 'BaldPhone - Alarm'
2. Click on 'Set an alarm'
3. Set alarm 1 minute in the future
4. Lock screen (without security features e.g. pin / face unlock)
5. Wait for alarm.

**Expected behavior**
Alarm should sound when screen is locked.

**Phone(please complete the following information, it can be found in the settings under Technical Information):**
 - API Level: 29
 - BaldPhone Version name: 12.1.4

**Additional context**
Phone: Nokia 3.2
Model: TA-1159

**Comment by EnfrigFalco** [comment]
Tried with F-Droid, seems to work with that.

**Comment by UriahShaulMandel** [comment]
Hi!
is BaldPhone set as your home screen?
this is a problematic issue!
Thank you for your contribution,
Uriah Shaul Mandel

**Comment by UriahShaulMandel** [comment]
fixed
