### ISSUE TITLE
Add more customizability to home screen

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#69]
**Is your feature request related to a problem? Please describe.**
- For example, Assistant doesn't work in all countries (like ours) and elderly in other countries mostly don't know english (which the assistant is based on)

**Describe the solution you'd like**

- Edit function to add the possibility to replace/change/move all buttons on home screen, not just WhatsApp

**Comment by Aokromes** [comment]
this was already implemented on https://github.com/UriahShaulMandel/BaldPhone/releases/tag/95 no?

**Comment by aha999** [comment]
Yes, but this issue hasn't been closed yet.
