### ISSUE TITLE
Add different colors to dialer's buttons

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#73]
For example "erase" could be red, "call" could be green, "backspace" could be orange, so it's easier to identify, instead of all the buttons being the same color.

**Comment by UriahShaulMandel** [comment]
Great idea, on it :)

**Comment by aha999** [comment]
Or perhaps just the colored icons inside the buttons, i don't know... what looks better i guess

**Comment by UriahShaulMandel** [comment]
#119 fixed it, Thanks @yonniii!

**Comment by aha999** [comment]
Looks nice, maybe the red delete color could be changed to something else imo
