### ISSUE TITLE
When clicking an app from an app drawer, don't open an optional window but just open the app

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#74]
When you click on an app in the app drawer, it opens a small window, where you can press "uninstall" or "add shortcut" by accident. 
It's way simpler if clicking an app just opens it and the uninstall/shortcut options are somewhere else.

**Comment by UriahShaulMandel** [comment]
Hi,
I disagree, I checked with some users which way is the best way to interact with apps, and PopUps was the best solution.
Most seniors use around 6 apps, which they pin to the HomeScreen.
So the Apps screen, will mostly be used to uninstall or add shortcuts to the HomeScreen,
Moving those options to somewhere else, IMO, makes this screen useless, to open apps faster the user can just go to page 4+ in the HomeScreen...
Remember the user base, most of BaldPhone's users are not really technological and won't need quick access to more than 30 apps, like me and probably you :)
Thank for the suggestion anyway! 


Also-
 - If they accidentally add Shortcut it can easily be reverted by clicking it again.
 - The uninstall button opens 2 new dialogs, to make sure it wasn't clicked by accident. The probability of clicking accidently `uninstall`, `yes` and `yes` again is close to zero...
