### ISSUE TITLE
No explanation text on what does "Clear cache" and "Clear all data" do ?

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#83]
**Is your feature request related to a problem? Please describe.**
There are options to clear cache and clear all data, but there's no explanation on what cache or what data it clears... Not knowing what does it do, kinda makes you scared to click the button.
Does it delete all the System data, BaldPhone data, sausage data ?

**Describe the solution you'd like**
A short, clear explanation in the text field above these two options, what does it do, and why would you click that.

**Comment by RigacciOrg** [comment]
I'm updating the Italian translation, so I wrote a little phrase for both the delete operations.
Translated into English they can sound like this:

For the `<string name="clear_cache_subtext">`

_Are you sure you want to delete the cache contents? Deleting temporary files may solve some app malfunctions, but also shortcuts created in the Home screen will be removed._

For the `<string name="clear_data_subtext">`

_Are you sure you want to delete all user data? The app will revert in a fresh-new state, as if it were just installed._

**Comment by aha999** [comment]
@RigacciOrg i think that the word 'baldphone' could also be added in the subtexst like "...delete BaldPhone data" so we know which user data is deleted and we don't assume it's cleaning of system data.

**Comment by RigacciOrg** [comment]
@aha999 Yea! Thanks! I updated the comment above.

**Comment by UriahShaulMandel** [comment]
Thanks, Adding it now!
