### ISSUE TITLE
When you select a level in the Select the level of accessability, the screen flashes black momentarily 

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#84]
When you select a level in the Select the level of accessability, the screen flashes black momentarily when the change is applied.

It would be better looking, if it did not flash at all.

**Comment by UriahShaulMandel** [comment]
OK, will be fixed
Note to self:
Use activity 'none' transition to self activity

**Comment by UriahShaulMandel** [comment]
Hi, I sat on it for some hours and here is my conclusion:

1. On most devices the screen won't flash
2. Removing the flash for all of the devices is possible, and I did manage to do it, but the cons of doing that (programmatically speaking) are not worth the removal of flashing in a small number of devices.

for those reasons, I reverted the fix and currently leaving it as is.
