### ISSUE TITLE
The "selected" text above the level of the accessability level could be visually connected to the level option

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#85]
**Is your feature request related to a problem? Please describe.**
The text above the accesability level is not clearly connected to the option

**Describe the solution you'd like**
Connect it with the option visually pleasing (directly connected with the black edges, and the "selected" box edges rounded on the top, inside of the box colored lightly green)

![eSPBP7dNXf](https://user-images.githubusercontent.com/50620416/67208981-d0242b80-f416-11e9-8e01-821febc0c0fc.png)

**Comment by UriahShaulMandel** [comment]
I think I'm just removing it, IMO it's not necessary and looks kinda weird,
because the two others are colored differently, I'm also adding an explanation in #137 ...

**Comment by aha999** [comment]
Sounds good
