### ISSUE TITLE
please make the app brand-free resp. more generic usable

### ISSUE THREAD

**Issue by DJCrashdummy** [UriahShaulMandel/BaldPhone#9]
- [x] the maps button seems to be hard-linked to google maps because when not installed, it just shows *"An error has occurred!"* instead of opening other installed map-apps like [SmartNavi](https://f-droid.org/packages/com.ilm.sandwich/), [OsmAnd](https://f-droid.org/packages/net.osmand.plus/), [Maps](https://f-droid.org/packages/com.github.axet.maps/), [PocketMaps](https://f-droid.org/packages/com.junjunguo.pocketmaps/) or [ZANavi](https://f-droid.org/packages/com.zoffcc.applications.zanavi/)/[Navit](https://f-droid.org/packages/org.navitproject.navit/) resp. the default map app.

- [x] the google button seems a kind of a waste of space (and camouflaged advertising) to me. instead a generic button named *"web-browser"* or *"internet"* and simply opening the default browser (with its default startpage resp. no special site) would make much more sense.

- [x] i'm not happy with the whatsapp icon either... not everyone (especially not older people) uses web-messengers or this particular service. - this causes real confusion!
i've no concrete idea to completely solve this problem for now, but probably a generic icon with *"web-messenger"* and a setting to choose your own app like e.g. [Riot.im](https://f-droid.org/packages/im.vector.alpha/) or any other would be at least reasonable.

**Comment by UriahShaulMandel** [comment]
Hi, and thank you for opening this issue!

This project started for helping one friend, so a lot of things were customized especially for him.

All of your points are really good and the platform should indeed become more generic. An update addressing these points will be published tomorrow.

Thanks again for helping to improve BaldPhone! :)

**Comment by DJCrashdummy** [comment]
> [...] thank you for opening this issue!

not a big deal... thank YOU for open sourcing your awesome work!

> This project started for helping one friend, so a lot of things were customized especially for him.

yes, i watched the video... very impressive and kudos to you both!

> All of your points are really good and the platform should indeed become more generic.

it was a pleasure bringing some input... and a honor that you agree with me.

**Comment by DJCrashdummy** [comment]
> i'm not happy with the whatsapp icon either...

perhaps a setting to choose *"e-Mail"* and your preferred e-Mail client instead, can be interesting (because it is mostly known and used also by older people).

but it still wouldn't be the perfect solution for all, because i also know enough older people, who neither use e-Mails (on mobile devices) nor Web-Messenger (or don't even know them at all) and have WiFi & mobile internet turned off usually... they pretty much use their smart phone as "advanced dumb phone" with alarm clock and camera.

**Comment by UriahShaulMandel** [comment]
All of the points were addressed :)
I hope you will like how I addressed the Whatsapp issue (go to settings -> personalization -> custom app)
if anything still bothers you, feel free to comment.

Thank you very much for opening all of your issues! 
You make BaldPhone better :)

**Comment by DJCrashdummy** [comment]
- ad whatsapp-issue:
brilliant! i guess the best solution possible... so not only the ones using whatever messenger or e-mail instead are satisfied, but even the ones who are using none of them can place there whatever app they want.

- ad internet:
why opening a blank page, instead of just the browser-app?

- ad maps:
at least other apps are opened by now, but why looking for Lat=0.0° Long=0.0°? - this is in best case just annoying and tedious, if you have to scroll around to your last used location every time you open the app.
BTW: also a generic map-icon would be appreciated.

- [ ] BTW generally about the 2nd screen:
having the normal apps (internet & maps) side by side and therefore separated by the tutorials from the settings makes IMHO more sense than it is ordered now, which seem to be completely random.

**Comment by UriahShaulMandel** [comment]
Hi, It took some time, but I finally got to a good result, which I think you'll like too.
 - When there are no maps\browsers applications, a toast containing "no matching apps were found" will be shown
 - When there is one app to open the specific intent, it'll simply appear there, with its icon and name (See Chrome)
 - When there is more than one app available, a generic icon and text will appear, and when clicked a dropdown menu will be shown with cool animation. clicking on an app will open it in its default state, no about:blanks or something.

# before clicking on maps


<img width="196" alt="Screenshot_9" src="https://user-images.githubusercontent.com/43012268/56077240-7e08aa80-5de2-11e9-9ceb-1d477f9244db.png">

# after clicking on maps

<img width="198" alt="Screenshot_10" src="https://user-images.githubusercontent.com/43012268/56077259-b6a88400-5de2-11e9-8a68-4119ebe73261.png">


Making some last tests and uploading soon

**Comment by DJCrashdummy** [comment]
beforehand one thing which is not completely clear to me: is the "after clicking" only shown once to choose a default, or every time? - if so, i'm pretty sure this is a bad UX!

---

apart from this: interesting and cool idea, **looks very nice**!

...**but** i'm not 100% sure, if it is the best solution for older people: i know a bunch of them who don't remember and/or not interested in the apps name. - some can distinguish their usual used programs/apps by their icon, but some even don't remember this.
*(for sure this also depends on the frequency they use this apps, but especially older people use the "more advanced apps" less frequently.)*

anyhow... **why make it more complicated than necessary?**
i have no idea if it is possible (my knowledge about android development is very limited), but simply opening the default app (without about_blank or geo:0,0-search) via generic names and icons would be the most straight forward solution.

**Comment by UriahShaulMandel** [comment]
I thought this would function like a folder, for example maps:
![Screenshot_20190414-152948_BaldPhone](https://user-images.githubusercontent.com/43012268/56092886-c3a0a280-5eca-11e9-84c7-da7a46c4ebbc.jpg)



![Screenshot_20190414-152953_BaldPhone](https://user-images.githubusercontent.com/43012268/56092867-76243580-5eca-11e9-87e0-3a10021db1de.jpg)


Most of the users will probably have one app to deal with each action anyway, so no "folder" will appear. I noticed a small bug and will fix it but please check the update I pushed, I think you will like it.

**Comment by breversa** [comment]
@DJCrashdummy : I too think that displaying WhatsApp *by default* is both confusing (for people who don't know/use it) and promotes a privacy-dangerous app (by portraying WhatsApp as the _de facto_ messaging app).

A generic "web messenger" that does not promote WhatsApp (or any other privacy-threatening app, actually) would go a long way towards better privacy-protecting practices.
Or even better : _suggest_ a privacy-friendly messenging app like [Signal](https://signal.org/) ! :+1:
