### ISSUE TITLE
Make SOS function optional (to turn it off in the settings)

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#92]
**Is your feature request related to a problem? Please describe.**
The SOS function can be annoying to some people, because they or someone else can press the "call emergency" by mistake and they would like the function turned off.

**Describe the solution you'd like**
Add an option in the settings to turn off the SOS function.

**Comment by UriahShaulMandel** [comment]
Hi, 
do you want the option to remove SOS button from the top bar of the home screen,
Or the Call Emergency button removed from the SOS screen?

**Comment by aha999** [comment]
My opinion:

- Maybe a new 'SOS options' menu in the settings would be required

- Option to change the emergency services number (which it calls by pressing the button)

- Option to remove the emergency services call button, which would (after that) automatically replace it with the 'one more slot' to add the contact/number like the two already above it.

**Comment by UriahShaulMandel** [comment]
Will leave this issue just as an option to remove SOS button from the top bar,

the other suggestions I'll add but it'll take some time. When dealing with SOS and emergency things, I tend to fear changes, which in life-saving moments won't be appreciated by the elderly which already got used to the current system. 
**I will do those changes**, but organized, with test group.
