### ISSUE TITLE
Github, Users and Users on Latest - links are not working

### ISSUE THREAD

**Issue by aha999** [UriahShaulMandel/BaldPhone#97]
![4s1totbLWn](https://user-images.githubusercontent.com/50620416/68029316-40ed0280-fcb7-11e9-89b3-5916b6d8fd44.png)

**Comment by UriahShaulMandel** [comment]
Hi, if you'll take a look at them now, they'll work
![image](https://user-images.githubusercontent.com/43012268/68038083-cd0c2380-fcd1-11e9-8453-31176c64d6f4.png)
I'm using a free hosting server for those, which doesn't work one hour a day. I currently don't have the funds to pay monthly for hosting server but perhaps in the future I'll have :)
currently, I'm closing this issue
